### ISSUE TITLE
Might wanna get a new bot token.

### ISSUE THREAD

**Issue by LikeLakers2** [Roadcrosser/Discord-Markov#2]
https://github.com/Roadcrosser/Discord-Markov/blob/master/markovbot.py#L36

You shouldn't ever put your bot token in a public Github repo. Those things can be abused.

I'd recommend removing it and generating a new token at https://discordapp.com/developers/applications/me.

**Comment by Roadcrosser** [comment]
That token had already been reset about 12 hours before I even uploaded it to GitHub, and I was just too lazy to change it into anything else when adding things to it prior.

Don't worry, it won't work.
